name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup .NET core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: install dependencies
        run: dotnet restore
      - name: build
        run: dotnet build --configuration Release --no-restore
      - name: test
        run: dotnet test --no-restore --verbosity normal
